# fly.toml app configuration file generated for hyperwave-news on 2025-06-12T12:45:30-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hyperwave-news'
primary_region = 'den'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  PORT = "8080"

[[mounts]]
  source = "data"
  destination = "/app/data"

[[vm]]
  size = 'shared-cpu-1x'
